TRACE T1 [main] org.apache.log4j.net.SocketServerTestCase Message 1
TRACE T1 [main] root Message 2
DEBUG T1 [main] org.apache.log4j.net.SocketServerTestCase Message 3
DEBUG T1 [main] root Message 4
 INFO T1 [main] org.apache.log4j.net.SocketServerTestCase Message 5
 WARN T1 [main] org.apache.log4j.net.SocketServerTestCase Message 6
FATAL T1 [main] org.apache.log4j.net.SocketServerTestCase Message 7
DEBUG T1 [main] org.apache.log4j.net.SocketServerTestCase Message 8
java.lang.Exception: Just testing
	at org.apache.log4j.net.SocketServerTestCase.common(SocketServerTestCase.java:XXX)
	at org.apache.log4j.net.SocketServerTestCase.test1(SocketServerTestCase.java:XXX)
	at junit.framework.TestCase.runTest(TestCase.java:XXX)
	at junit.framework.TestCase.runBare(TestCase.java:XXX)
	at junit.framework.TestResult$1.protect(TestResult.java:XXX)
	at junit.framework.TestResult.runProtected(TestResult.java:XXX)
	at junit.framework.TestResult.run(TestResult.java:XXX)
	at junit.framework.TestCase.run(TestCase.java:XXX)
	at junit.framework.TestSuite.runTest(TestSuite.java:XXX)
	at junit.framework.TestSuite.run(TestSuite.java:XXX)
ERROR T1 [main] root Message 9
java.lang.Exception: Just testing
	at org.apache.log4j.net.SocketServerTestCase.common(SocketServerTestCase.java:XXX)
	at org.apache.log4j.net.SocketServerTestCase.test1(SocketServerTestCase.java:XXX)
	at junit.framework.TestCase.runTest(TestCase.java:XXX)
	at junit.framework.TestCase.runBare(TestCase.java:XXX)
	at junit.framework.TestResult$1.protect(TestResult.java:XXX)
	at junit.framework.TestResult.runProtected(TestResult.java:XXX)
	at junit.framework.TestResult.run(TestResult.java:XXX)
	at junit.framework.TestCase.run(TestCase.java:XXX)
	at junit.framework.TestSuite.runTest(TestSuite.java:XXX)
	at junit.framework.TestSuite.run(TestSuite.java:XXX)
