TRACE T2 [main] SocketServerTestCase (socketservertestcase.cpp:XXX) Message 1
TRACE T2 [main] SocketServerTestCase (socketservertestcase.cpp:XXX) Message 2
DEBUG T2 [main] SocketServerTestCase (socketservertestcase.cpp:XXX) Message 3
DEBUG T2 [main] SocketServerTestCase (socketservertestcase.cpp:XXX) Message 4
 INFO T2 [main] SocketServerTestCase (socketservertestcase.cpp:XXX) Message 5
 WARN T2 [main] SocketServerTestCase (socketservertestcase.cpp:XXX) Message 6
FATAL T2 [main] SocketServerTestCase (socketservertestcase.cpp:XXX) Message 7
DEBUG T2 [main] SocketServerTestCase (socketservertestcase.cpp:XXX) Message 8
java.lang.Exception: Just testing
	at org.apache.log4j.net.SocketServerTestCase.common(SocketServerTestCase.java:XXX)
	at org.apache.log4j.net.SocketServerTestCase.test2(SocketServerTestCase.java:XXX)
	at junit.framework.TestCase.runTest(TestCase.java:XXX)
	at junit.framework.TestCase.runBare(TestCase.java:XXX)
	at junit.framework.TestResult$1.protect(TestResult.java:XXX)
	at junit.framework.TestResult.runProtected(TestResult.java:XXX)
	at junit.framework.TestResult.run(TestResult.java:XXX)
	at junit.framework.TestCase.run(TestCase.java:XXX)
	at junit.framework.TestSuite.runTest(TestSuite.java:XXX)
	at junit.framework.TestSuite.run(TestSuite.java:XXX)
ERROR T2 [main] SocketServerTestCase (socketservertestcase.cpp:XXX) Message 9
java.lang.Exception: Just testing
	at org.apache.log4j.net.SocketServerTestCase.common(SocketServerTestCase.java:XXX)
	at org.apache.log4j.net.SocketServerTestCase.test2(SocketServerTestCase.java:XXX)
	at junit.framework.TestCase.runTest(TestCase.java:XXX)
	at junit.framework.TestCase.runBare(TestCase.java:XXX)
	at junit.framework.TestResult$1.protect(TestResult.java:XXX)
	at junit.framework.TestResult.runProtected(TestResult.java:XXX)
	at junit.framework.TestResult.run(TestResult.java:XXX)
	at junit.framework.TestCase.run(TestCase.java:XXX)
	at junit.framework.TestSuite.runTest(TestSuite.java:XXX)
	at junit.framework.TestSuite.run(TestSuite.java:XXX)
