TRACE some6 T6 client-test6 MDC-TEST6 [main] SocketServerTestCase - Message 1
TRACE some6 T6 client-test6 MDC-TEST6 [main] root - Message 2
DEBUG some6 T6 client-test6 MDC-TEST6 [main] SocketServerTestCase - Message 3
DEBUG some6 T6 client-test6 MDC-TEST6 [main] root - Message 4
 INFO some6 T6 client-test6 MDC-TEST6 [main] SocketServerTestCase - Message 5
 WARN some6 T6 client-test6 MDC-TEST6 [main] SocketServerTestCase - Message 6
FATAL some6 T6 client-test6 MDC-TEST6 [main] SocketServerTestCase - Message 7
DEBUG some6 T6 client-test6 MDC-TEST6 [main] SocketServerTestCase - Message 8
java.lang.Exception: Just testing
	at org.apache.log4j.net.SocketServerTestCase.common(SocketServerTestCase.java:XXX)
	at org.apache.log4j.net.SocketServerTestCase.test6(SocketServerTestCase.java:XXX)
	at junit.framework.TestCase.runTest(TestCase.java:XXX)
	at junit.framework.TestCase.runBare(TestCase.java:XXX)
	at junit.framework.TestResult$1.protect(TestResult.java:XXX)
	at junit.framework.TestResult.runProtected(TestResult.java:XXX)
	at junit.framework.TestResult.run(TestResult.java:XXX)
	at junit.framework.TestCase.run(TestCase.java:XXX)
	at junit.framework.TestSuite.runTest(TestSuite.java:XXX)
	at junit.framework.TestSuite.run(TestSuite.java:XXX)
ERROR some6 T6 client-test6 MDC-TEST6 [main] root - Message 9
java.lang.Exception: Just testing
	at org.apache.log4j.net.SocketServerTestCase.common(SocketServerTestCase.java:XXX)
	at org.apache.log4j.net.SocketServerTestCase.test6(SocketServerTestCase.java:XXX)
	at junit.framework.TestCase.runTest(TestCase.java:XXX)
	at junit.framework.TestCase.runBare(TestCase.java:XXX)
	at junit.framework.TestResult$1.protect(TestResult.java:XXX)
	at junit.framework.TestResult.runProtected(TestResult.java:XXX)
	at junit.framework.TestResult.run(TestResult.java:XXX)
	at junit.framework.TestCase.run(TestCase.java:XXX)
	at junit.framework.TestSuite.runTest(TestSuite.java:XXX)
	at junit.framework.TestSuite.run(TestSuite.java:XXX)
