TRACE some T4 MDC-TEST4 [main] SocketServerTestCase - Message 1
TRACE some T4 MDC-TEST4 [main] root - Message 2
DEBUG some T4 MDC-TEST4 [main] SocketServerTestCase - Message 3
DEBUG some T4 MDC-TEST4 [main] root - Message 4
 INFO some T4 MDC-TEST4 [main] SocketServerTestCase - Message 5
 WARN some T4 MDC-TEST4 [main] SocketServerTestCase - Message 6
FATAL some T4 MDC-TEST4 [main] SocketServerTestCase - Message 7
DEBUG some T4 MDC-TEST4 [main] SocketServerTestCase - Message 8
java.lang.Exception: Just testing
	at org.apache.log4j.net.SocketServerTestCase.common(SocketServerTestCase.java:XXX)
	at org.apache.log4j.net.SocketServerTestCase.test4(SocketServerTestCase.java:XXX)
	at junit.framework.TestCase.runTest(TestCase.java:XXX)
	at junit.framework.TestCase.runBare(TestCase.java:XXX)
	at junit.framework.TestResult$1.protect(TestResult.java:XXX)
	at junit.framework.TestResult.runProtected(TestResult.java:XXX)
	at junit.framework.TestResult.run(TestResult.java:XXX)
	at junit.framework.TestCase.run(TestCase.java:XXX)
	at junit.framework.TestSuite.runTest(TestSuite.java:XXX)
	at junit.framework.TestSuite.run(TestSuite.java:XXX)
ERROR some T4 MDC-TEST4 [main] root - Message 9
java.lang.Exception: Just testing
	at org.apache.log4j.net.SocketServerTestCase.common(SocketServerTestCase.java:XXX)
	at org.apache.log4j.net.SocketServerTestCase.test4(SocketServerTestCase.java:XXX)
	at junit.framework.TestCase.runTest(TestCase.java:XXX)
	at junit.framework.TestCase.runBare(TestCase.java:XXX)
	at junit.framework.TestResult$1.protect(TestResult.java:XXX)
	at junit.framework.TestResult.runProtected(TestResult.java:XXX)
	at junit.framework.TestResult.run(TestResult.java:XXX)
	at junit.framework.TestCase.run(TestCase.java:XXX)
	at junit.framework.TestSuite.runTest(TestSuite.java:XXX)
	at junit.framework.TestSuite.run(TestSuite.java:XXX)
